# Generated by Django 4.2.7 on 2026-06-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo / Image'), ('video', 'Video')], max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='Size in KB')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('fake', 'Fake'), ('real', 'Real'), ('suspicious', 'Suspicious')], max_length=20)),
                ('fake_score', models.IntegerField(help_text='0-100, higher = more likely fake')),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('warnings_found', models.PositiveIntegerField(default=0)),
                ('checks_json', models.TextField(default='[]')),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
